### ISSUE TITLE
Preset Dashboards yield Blank Panel: Socket hang up / Metric was not found

### ISSUE THREAD

**Issue by sw-mreyes** [opendistro-for-elasticsearch/perftop#21]
Perftop shows a blank dashboard for all preset dashboards:

- `./perf-top-linux --dashboard ClusterNetworkMemoryAnalysis --endpoint http://127.0.0.1:9200 --logfile ` [cnma.txt](https://gist.github.com/sw-mreyes/c301dcf9b18f8cb0f7aafb94fc3b16e6)

        Metric was not found for request with queryParams:
                endpoint: http://127.0.0.1:9200
                metrics: Net_Throughput
                agg:sum
        dim:Direction
- `./perf-top-linux --dashboard ClusterOverview --endpoint http://127.0.0.1:9200 --logfile ` [co.txt](https://gist.github.com/sw-mreyes/a2ec5991ea9ba3875caa0f7581c3234a)

        Metric was not found for request with queryParams:
                endpoint: http://127.0.0.1:9200
                metrics: CPU_Utilization
                agg:sum
        dim:Operation
- `./perf-top-linux --dashboard ClusterThreadAnalysis --endpoint http://127.0.0.1:9200 --logfile ` [cta.txt](https://gist.github.com/sw-mreyes/6c937cca9398b07c797226c039f0ea37)

        Failed to retrieve units for metrics. HTTP(S) response was empty.
- `./perf-top-linux --dashboard NodeAnalysis --endpoint http://127.0.0.1:9200 --logfile ` [na.txt](https://gist.github.com/sw-mreyes/245655a83dc981f45f6f5aa9dae3de64)

To test that the API is reachable (and returns json) I tried the following:

    curl -XGET "http://localhost:9600/_opendistro/_performanceanalyzer/metrics?metrics=Latency,CPU_Utilization&agg=avg,max&dim=ShardID&nodes=all"

    {
       "BcrhuVNCTp28dBc7Qb_fuA":{
          "timestamp":1560762180000,
          "data":{
             "fields":[
                {
                   "name":"ShardID",
                   "type":"VARCHAR"
                },
                {
                   "name":"Latency",
                   "type":"DOUBLE"
                },
                {
                   "name":"CPU_Utilization",
                   "type":"DOUBLE"
                }
             ],
             "records":[
    
             ]
          }
       }
    }

Which did work as expected.

#### Version Information
- opendistro-performance-analyzer 0.9.0.0-1 
- opendistroforelasticsearch 0.9.0-1
- opendistroforelasticsearch-kibana 0.9.0
- perf-top-0.9.0.0-LINUX([.zip](https://opendistro.github.io/for-elasticsearch/downloads.html))

**Comment by ditac** [comment]
Please change the endpoint that you have given perf-top to be "localhost:9600". The command you need to run should be - 
```
./perf-top-linux --dashboard ClusterOverview --endpoint http://localhost:9600
```

**Comment by Yalkun87** [comment]
> Please change the endpoint that you have given perf-top to be "localhost:9600". The command you need to run should be -
> 
> ```
> ./perf-top-linux --dashboard ClusterOverview --endpoint http://localhost:9600
> ```

not working, error output
Data returned for nodeName=local was in an unexpected format:
        {"timestamp":1599037185000,"data":{}}
Data returned for nodeName=local was in an unexpected format:
        {"timestamp":1599037190000,"data":{}}
Data returned for nodeName=local was in an unexpected format:
        {"timestamp":1599037190000,"data":{}}
Data returned for nodeName=local was in an unexpected format:
        {"timestamp":1599037190000,"data":{}}
Data returned for nodeName=local was in an unexpected format:
        {"timestamp":1599037190000,"data":{}}
Data returned for nodeName=local was in an unexpected format:
        {"timestamp":1599037190000,"data":{}}
Metric was not found for request with queryParams:

        endpoint: http://localhost:9600

        metrics: Net_Throughput

        agg:sum

        dim:Direction
Data returned for nodeName=local was in an unexpected format:
        {"timestamp":1599037190000,"data":{}}
Metric was not found for request with queryParams:

        endpoint: http://localhost:9600

        metrics: Net_Throughput

        agg:sum

        dim:Direction
