### ISSUE TITLE
Does not support connecting to clusters with basic auth

### ISSUE THREAD

**Issue by keety** [opendistro-for-elasticsearch/perftop#34]
The perf-top client does not support connecting to clusters with basic auth.
the options does not support basic auth
```
perf-top
usage: global.js [-h] --dashboard DASHBOARD [--endpoint ENDPOINT]
                 [--nodename NODENAME] [--logfile LOGFILE]
```
nor can one pass an endpoint as follows:
```
 perf-top --endpoint https://username:password@cluster_endpoint --dashboard ClusterOverview
```

**Comment by sendkb** [comment]
Fixed as a part of https://github.com/opendistro-for-elasticsearch/perftop/pull/35
