### ISSUE TITLE
Using PerfTop in a managed Cluster (Amazon Elasticsearch)

### ISSUE THREAD

**Issue by rafael-gumiero** [opendistro-for-elasticsearch/perftop#65]
I would like to validate whether there is support for using PerfTop in a managed cluster (Amazon Elasticsearch)

**Comment by ricardolstephen** [comment]
I don't see anything about it in their documentation:
https://docs.aws.amazon.com/elasticsearch-service

**Comment by rafael-gumiero** [comment]
So far it is not available on the managed service.
