### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by natefox** [opendistro-for-elasticsearch/perftop#8]
When I use `--endpoint https://my.site.com` I get
```{ Error: getaddrinfo ENOTFOUND https https:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'https',
  host: 'https',
  port: 80 }
```

When I use `--endpoint my.site.com:443` I get 
```        <html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
</body>
</html>
```

It would also be helpful to be able to ignore tls warnings as we have self signed certs for some clusters ala curl's `-k` switch:
```
 -k, --insecure      Allow connections to SSL sites without certs (H)
```

**Comment by yeajung** [comment]
Apologies for the late response.

PerfTop currently uses the HTTP library and therefore supports only HTTP. We will be looking into HTTPS support soon.

Thanks.

**Comment by yeajung** [comment]
This has been addressed in https://github.com/opendistro-for-elasticsearch/perftop/pull/19
